(ns example-rest-api.const)


(def api-version "0.1.0")

; HTTP 1xx
(def continue 100)
(def switching-protocols 101)
(def processing 102)
; HTTP 2xx
(def ok 200)
(def created 201)
(def accepted 202)
(def non-authoritative-information 203)
(def no-content 204)
(def reset-content 205)
(def partial-content 206)
(def multi-status 207)
(def already-reported 208)
(def im-used 226)
; HTTP 3xx
(def multiple-choices 300)
(def moved-permanently 301)
(def found 302)
(def see-other 303)
(def not-modified 304)
(def use-proxy 305)
(def switch-proxy 306)
(def temporary-redirect 307)
(def permanent-redirect 308)
; HTTP 4xx
(def bad-request 400)
(def unauthorized 401)
(def payment-required 402)
(def forbidden 403)
(def not-found 404)
(def method-not-allowed 405)
(def not-acceptable 406)
(def proxy-authentication-required 407)
(def request-timeout 408)
(def conflict 409)
(def gone 410)
(def length-required 411)
(def precondition-failed 412)
(def request-entity-too-large 413)
(def request-uri-too-long 414)
(def unsupported-media-type 415)
(def requested-range-not-satisfiable 416)
(def expectation-failed 417)
(def im-a-teapot 418)
(def authentication-timeout 419)
;(def method-failure 420)
;(def enhance-your-calm 420)
(def unprocessable-entity 422)
(def locked 423)
;(def failed-dependency 422)
(def method-failure 422)
(def unordered-collection 425)
(def upgrade-required 426)
(def precondition-required 428)
(def too-many-requests 429)
(def request-header-fields-too-large 431)
(def no-response 444)
;(def retry-with 449)
;(def blocked-by-windows-parental-controls 450)
(def unavailable-for-legal-reasons 451)
;(def redirect 451)
(def request-header-too-large 494)
(def cert-error 495)
(def no-cert 496)
(def http-to-https 497)
(def client-closed-request 499)
; HTTP 5xx
(def internal-server-error 500)
(def not-implemented 501)
(def bad-gateway 502)
(def service-unavailable 503)
(def gateway-timeout 504)
(def http-version-not-supported 505)
(def variant-also-negotiates 506)
(def insufficient-storage 507)
(def loop-detected 508)
(def bandwidth-limit-exceeded 509)
(def not-extended 510)
(def network-authentication-required 511)
(def connection-timed-out 522)
;(def network-read-timeout-error 598)
;(def network-connect-timeout-error 599)

(def four-oh-four-message
  "Twas bryllyg, and ye slythy toves <br/>
  Did gyre and gymble in ye wabe: <br/>
  All mimsy were ye borogoves; <br/>
  And ye four-oh-fours outgrabe.<br/>")
