language: erlang
script: "make check-travis"
notifications:
  irc: "irc.freenode.org#adytum
  recipients:
    - oubiwann@gmail.com
otp_release:
  - 18.0
  - 17.5
  - R16B03
  - R15B03
before_install:
  - sudo apt-get install libpam0g-dev
